### ISSUE TITLE
Task: Dataset Submission

### ISSUE THREAD

**Issue by mkrangle** [mitll/PACT#5]
https://github.com/mkrangle/MITRE-Range-Angle-Unstructured

**Comment by cassiecorey** [comment]
Can I take one of the photos mentioned in the README for the card image?

I think this one looks good: https://github.com/mkrangle/MITRE-Range-Angle-Unstructured/blob/master/CF1/txRxDiagram.png

**Comment by cassiecorey** [comment]
We've added the dataset to the website. Thank you for your submission!
