### ISSUE TITLE
Task: Dataset Submission

### ISSUE THREAD

**Issue by mkrangle** [mitll/PACT#7]
https://github.com/mkrangle/MITRE-Range-Angle-Structured

**Comment by cassiecorey** [comment]
Dataset has been added to the website. However, I'm using the same card image as from the "Unstructured" dataset. @mkrangle Do you have a different image you'd like to use?

(accidentally flipped the descriptions for structured/unstructured but you should see it refresh shortly, if not already)

**Comment by cassiecorey** [comment]
Updated the image to this one:

![MITRE-Range-Angle-Structured](https://user-images.githubusercontent.com/8444201/86367702-4afe4100-bc4a-11ea-9f01-b3ed48a98534.jpeg)
